server:
  error:
    include-message: always
  port: ${HOST_PORT:9020}
spring:
  application:
    name: @project.name@
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      group-id: ${spring.application.name}
      autoOffsetReset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
logging:
  level:
    org.springframework.security: TRACE
jwt:
  auth:
    converter:
      resource-id: student-app
      principal-attribute: preferred_name
kafka:
  topic:
    students: students
    users: users
  timeout: 2000
keycloak:
  realm: ${KEYCLOAK_REALM:student-realm}
  host: ${KEYCLOAK_HOST:http://localhost:8484}
  token-endpoint: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token