server:
  error:
    include-message: always
  port: ${HOST_PORT:9010}
spring:
  application:
    name: @project.name@
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:student}?ApplicationName=${spring.application.name}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${spring.application.name}
      autoOffsetReset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9030}/eureka/
minio:
  url: ${MINIO_URL:http://127.0.0.1:9000}
  bucket: ${MINIO_BUCKET:image-storage}
  username: ${MINIO_USERNAME:minioadmin}
  password: ${MINIO_PASSWORD:minioadmin}