server:
  error:
    include-message: always
  port: ${HOST_PORT:9020}
spring:
  application:
    name: @project.name@
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 900MB
      max-request-size: 900MB
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9030}/eureka/