//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.18 at 02:47:06 PM KRAT 
//


package ru.bekhterev.studentservicesoap;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faculty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="faculty"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ARTS"/&gt;
 *     &lt;enumeration value="CLASSICS"/&gt;
 *     &lt;enumeration value="COMMERCE"/&gt;
 *     &lt;enumeration value="ECONOMICS"/&gt;
 *     &lt;enumeration value="EDUCATION"/&gt;
 *     &lt;enumeration value="ENGINEERING"/&gt;
 *     &lt;enumeration value="HEALTH"/&gt;
 *     &lt;enumeration value="HUMANITIES"/&gt;
 *     &lt;enumeration value="IT"/&gt;
 *     &lt;enumeration value="LAW"/&gt;
 *     &lt;enumeration value="PHILOSOPHY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "faculty")
@XmlEnum
public enum Faculty {

    ARTS,
    CLASSICS,
    COMMERCE,
    ECONOMICS,
    EDUCATION,
    ENGINEERING,
    HEALTH,
    HUMANITIES,
    IT,
    LAW,
    PHILOSOPHY;

    public String value() {
        return name();
    }

    public static Faculty fromValue(String v) {
        return valueOf(v);
    }

}
