//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.17 at 04:40:43 PM HOVT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.bekhterev.ru/studentservicesoap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.bekhterev.studentservicesoap;
