server:
  error:
    include-message: always
  port: ${HOST_PORT:9010}
spring:
  application:
    name: @project.name@
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 900MB
      max-request-size: 900MB
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:student}?ApplicationName=${spring.application.name}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      group-id: ${spring.application.name}
      autoOffsetReset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka:
  topic:
    students: students
    users: users
minio:
  url: ${MINIO_URL:http://127.0.0.1:9000}
  bucket: ${MINIO_BUCKET:image-storage}
  username: ${MINIO_USERNAME:minioadmin}
  password: ${MINIO_PASSWORD:minioadmin}