server:
  port: ${HOST_PORT:9000}
eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
spring:
  application:
    name: student-eureka-server
cloud:
  loadbalancer:
    ribbon:
      enabled: false
