//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.20 at 11:44:30 AM HOVT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.bekhterev.ru/sservice/xml", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.bekhterev.sservice.xml;
